In [197]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt


In [198]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
X.shape

(150, 4)

In [199]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_test.shape

(30, 4)

In [200]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train)
X_test_norm = scaler.fit_transform(X_test)
X_train_norm

array([[-1.28466206, -0.12163352, -1.33790752, -1.18371106],
       [-1.0366179 ,  0.55202904, -1.33790752, -1.31696184],
       [-1.16063998,  0.10292067, -1.28060955, -1.45021262],
       [ 1.31980165,  0.10292067,  0.95401114,  1.21480291],
       [-1.0366179 , -1.69351281, -0.24924615, -0.25095563],
       [ 1.81588997, -0.3461877 ,  1.46969284,  0.81505058],
       [ 1.69186789,  1.22569159,  1.35509691,  1.74780602],
       [-1.0366179 ,  0.77658322, -1.28060955, -1.31696184],
       [ 0.57566916, -0.57074189,  0.78211724,  0.41529825],
       [ 1.19577957,  0.32747485,  1.24050097,  1.48130446],
       [ 1.07175749,  0.55202904,  1.12590504,  1.21480291],
       [-0.41650749,  2.5730167 , -1.33790752, -1.31696184],
       [ 0.57566916,  0.55202904,  0.55292538,  0.54854903],
       [-0.91259581,  1.45024578, -1.28060955, -1.05046029],
       [ 0.69969124, -0.57074189,  1.06860708,  1.34805369],
       [ 1.93991205, -0.57074189,  1.35509691,  0.94830136],
       [ 0.69969124, -0.

In [201]:
from sklearn.linear_model import LogisticRegression
clr_LR = LogisticRegression()

In [202]:
clr_LR.fit(X_train_norm, y_train)

LogisticRegression()

In [203]:
clr_LR.intercept_

array([-0.26363296,  1.90654543, -1.64291247])

In [204]:
clr_LR.coef_

array([[-0.98030048,  1.06205679, -1.81062237, -1.71325949],
       [ 0.57101706, -0.44747134, -0.27955199, -0.75960701],
       [ 0.40928341, -0.61458545,  2.09017436,  2.47286649]])

In [205]:
y_pred = clr_LR.predict(X_test_norm)

In [206]:
y_test

array([0, 2, 0, 2, 1, 2, 2, 1, 2, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 0, 2, 0,
       0, 0, 0, 1, 0, 0, 1, 2])

In [207]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9666666666666667